kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: carbide
  namespace: fleet-default
spec:
  repo: https://github.com/rancherfederal/norseman_fleet.git
  branch: main

  # To target specific clusters, uncomment this block
  targets:
  - clusterSelector:
      matchLabels:
        environment: ctoroadshow

  paths:
  - "./gitops/apps/carbide"